export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_ALL_ITEM = "REMOVE_ALL_ITEM";
export const TOTAL_ITEMS = "TOTAL_ITEMS";
export const LOCAL_STORAGE_CART = "LOCAL_STORAGE_CART";
export const LOAD_CART_PRODUCTS = "LOAD_CART_PRODUCTS";
export const UPDATE_CART_PRODUCTS = "UPDATE_CART_PRODUCTS";
