export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const USER_NAME = "USER_NAME";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const GET_ALL_GAMES = "GET_ALL_GAMES";
export const CREATE_NEW_GAME = "CREATE_NEW_GAME";
export const EDIT_GAME = "EDIT_GAME";
export const REMOVE_GAME = "REMOVE_GAME";
export const OPEN_EDIT_MODAL = "OPEN_EDIT_MODAL";
export const CLOSE_EDIT_MODAL = "CLOSE_EDIT_MODAL";

export const FETCH_GAME_REQUEST = "FETCH_GAME_REQUEST";
export const FETCH_GAME_FAILURE = "FETCH_GAME_FAILURE";
export const FETCH_GAME_SUCCESS = "FETCH_GAME_SUCCESS";
export const DELETE_SET_SUCCESS = "DELETE_SET_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_ALL_ITEM = "REMOVE_ALL_ITEM";
export const TOTAL_ITEMS = "TOTAL_ITEMS";
export const LOCAL_STORAGE_CART = "LOCAL_STORAGE_CART";
